#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 26 16:27:52 PDT 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim BIT5_FROM_LFSR_behav -key {Behavioral:sim_1:Functional:BIT5_FROM_LFSR} -tclbatch BIT5_FROM_LFSR.tcl -log simulate.log"
xsim BIT5_FROM_LFSR_behav -key {Behavioral:sim_1:Functional:BIT5_FROM_LFSR} -tclbatch BIT5_FROM_LFSR.tcl -log simulate.log

